name: Release

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    uses: legitmark-eng/.github/.github/workflows/release.yml@main
    with:
      project_name: "Legitmark TypeScript"
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      ORG_READ_TOKEN: ${{ secrets.ORG_READ_TOKEN }}
